"""add dispatch_events for analytics consumer

Revision ID: 7301e5e171e8
Revises: b4d0116aefb1
Create Date: 2026-07-30 15:20:02.178728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7301e5e171e8'
down_revision: Union[str, Sequence[str], None] = 'b4d0116aefb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatch_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('rider_id', sa.Integer(), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('kafka_partition', sa.Integer(), nullable=False),
    sa.Column('kafka_offset', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispatch_events_id'), 'dispatch_events', ['id'], unique=False)
    op.create_index(op.f('ix_dispatch_events_order_id'), 'dispatch_events', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_events_order_id'), table_name='dispatch_events')
    op.drop_index(op.f('ix_dispatch_events_id'), table_name='dispatch_events')
    op.drop_table('dispatch_events')
    # ### end Alembic commands ###
