"""add rider_id to orders

Revision ID: b4d0116aefb1
Revises: a672f251ffaf
Create Date: 2026-06-27 06:38:30.106576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d0116aefb1'
down_revision: Union[str, Sequence[str], None] = 'a672f251ffaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('rider_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'riders', ['rider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'rider_id')
    # ### end Alembic commands ###
